/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorReviewsRouteImport } from './routes/vendor.reviews'
import { Route as VendorReportsRouteImport } from './routes/vendor.reports'
import { Route as VendorPreparationRouteImport } from './routes/vendor.preparation'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorMessagesRouteImport } from './routes/vendor.messages'
import { Route as VendorImportExportRouteImport } from './routes/vendor.import-export'
import { Route as ShopVendorIdRouteImport } from './routes/shop.$vendorId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as CCategoryIdRouteImport } from './routes/c.$categoryId'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPreparationRouteImport } from './routes/admin.preparation'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCountriesRouteImport } from './routes/admin.countries'
import { Route as AdminContactSettingsRouteImport } from './routes/admin.contact-settings'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCommissionOrdersRouteImport } from './routes/admin.commission-orders'
import { Route as AdminCategoryRequestsRouteImport } from './routes/admin.category-requests'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as VendorProductsIndexRouteImport } from './routes/vendor.products.index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'
import { Route as OrdersOrderIdValidateShipmentRouteImport } from './routes/orders.$orderId.validate-shipment'
import { Route as ApiPublicInngestRouteImport } from './routes/api/public/inngest'
import { Route as AdminSupportConversationIdRouteImport } from './routes/admin.support.$conversationId'
import { Route as AdminCustomersUserIdRouteImport } from './routes/admin.customers.$userId'
import { Route as AdminCommissionsViewRouteImport } from './routes/admin.commissions.view'
import { Route as AdminCommissionsHubRouteImport } from './routes/admin.commissions.hub'
import { Route as VendorProductsProductIdEditRouteImport } from './routes/vendor.products.$productId.edit'
import { Route as AdminShopsShopIdManageRouteImport } from './routes/admin.shops_.$shopId.manage'
import { Route as AdminShopsShopIdImportExportRouteImport } from './routes/admin.shops_.$shopId.import-export'
import { Route as AdminShopsShopIdGeneratorRouteImport } from './routes/admin.shops_.$shopId.generator'
import { Route as AdminProductsProductIdModerateRouteImport } from './routes/admin.products.$productId.moderate'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin.products.$productId.edit'
import { Route as AdminShopsShopIdProductsNewRouteImport } from './routes/admin.shops_.$shopId.products.new'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReviewsRoute = VendorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReportsRoute = VendorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPreparationRoute = VendorPreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => VendorRoute,
} as any)
const VendorMessagesRoute = VendorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => VendorRoute,
} as any)
const VendorImportExportRoute = VendorImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => VendorRoute,
} as any)
const ShopVendorIdRoute = ShopVendorIdRouteImport.update({
  id: '/shop/$vendorId',
  path: '/shop/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIdRoute = CCategoryIdRouteImport.update({
  id: '/c/$categoryId',
  path: '/c/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreparationRoute = AdminPreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactSettingsRoute = AdminContactSettingsRouteImport.update({
  id: '/contact-settings',
  path: '/contact-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionOrdersRoute = AdminCommissionOrdersRouteImport.update({
  id: '/commission-orders',
  path: '/commission-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoryRequestsRoute = AdminCategoryRequestsRouteImport.update({
  id: '/category-requests',
  path: '/category-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsIndexRoute = VendorProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => VendorRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => VendorRoute,
} as any)
const OrdersOrderIdValidateShipmentRoute =
  OrdersOrderIdValidateShipmentRouteImport.update({
    id: '/$orderId/validate-shipment',
    path: '/$orderId/validate-shipment',
    getParentRoute: () => OrdersRoute,
  } as any)
const ApiPublicInngestRoute = ApiPublicInngestRouteImport.update({
  id: '/api/public/inngest',
  path: '/api/public/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportConversationIdRoute =
  AdminSupportConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AdminSupportRoute,
  } as any)
const AdminCustomersUserIdRoute = AdminCustomersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCommissionsViewRoute = AdminCommissionsViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AdminCommissionsRoute,
} as any)
const AdminCommissionsHubRoute = AdminCommissionsHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AdminCommissionsRoute,
} as any)
const VendorProductsProductIdEditRoute =
  VendorProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => VendorRoute,
  } as any)
const AdminShopsShopIdManageRoute = AdminShopsShopIdManageRouteImport.update({
  id: '/shops_/$shopId/manage',
  path: '/shops/$shopId/manage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsShopIdImportExportRoute =
  AdminShopsShopIdImportExportRouteImport.update({
    id: '/shops_/$shopId/import-export',
    path: '/shops/$shopId/import-export',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShopsShopIdGeneratorRoute =
  AdminShopsShopIdGeneratorRouteImport.update({
    id: '/shops_/$shopId/generator',
    path: '/shops/$shopId/generator',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsProductIdModerateRoute =
  AdminProductsProductIdModerateRouteImport.update({
    id: '/$productId/moderate',
    path: '/$productId/moderate',
    getParentRoute: () => AdminProductsRoute,
  } as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => AdminProductsRoute,
  } as any)
const AdminShopsShopIdProductsNewRoute =
  AdminShopsShopIdProductsNewRouteImport.update({
    id: '/shops_/$shopId/products/new',
    path: '/shops/$shopId/products/new',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/category-requests': typeof AdminCategoryRequestsRoute
  '/admin/commission-orders': typeof AdminCommissionOrdersRoute
  '/admin/commissions': typeof AdminCommissionsRouteWithChildren
  '/admin/contact-settings': typeof AdminContactSettingsRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preparation': typeof AdminPreparationRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/vendors': typeof AdminVendorsRoute
  '/c/$categoryId': typeof CCategoryIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$vendorId': typeof ShopVendorIdRoute
  '/vendor/import-export': typeof VendorImportExportRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/preparation': typeof VendorPreparationRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/commissions/hub': typeof AdminCommissionsHubRoute
  '/admin/commissions/view': typeof AdminCommissionsViewRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/support/$conversationId': typeof AdminSupportConversationIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/orders/$orderId/validate-shipment': typeof OrdersOrderIdValidateShipmentRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/products/$productId/moderate': typeof AdminProductsProductIdModerateRoute
  '/admin/shops/$shopId/generator': typeof AdminShopsShopIdGeneratorRoute
  '/admin/shops/$shopId/import-export': typeof AdminShopsShopIdImportExportRoute
  '/admin/shops/$shopId/manage': typeof AdminShopsShopIdManageRoute
  '/vendor/products/$productId/edit': typeof VendorProductsProductIdEditRoute
  '/admin/shops/$shopId/products/new': typeof AdminShopsShopIdProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/category-requests': typeof AdminCategoryRequestsRoute
  '/admin/commission-orders': typeof AdminCommissionOrdersRoute
  '/admin/commissions': typeof AdminCommissionsRouteWithChildren
  '/admin/contact-settings': typeof AdminContactSettingsRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preparation': typeof AdminPreparationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/vendors': typeof AdminVendorsRoute
  '/c/$categoryId': typeof CCategoryIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$vendorId': typeof ShopVendorIdRoute
  '/vendor/import-export': typeof VendorImportExportRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/preparation': typeof VendorPreparationRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/admin/commissions/hub': typeof AdminCommissionsHubRoute
  '/admin/commissions/view': typeof AdminCommissionsViewRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/support/$conversationId': typeof AdminSupportConversationIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/orders/$orderId/validate-shipment': typeof OrdersOrderIdValidateShipmentRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/vendor/products': typeof VendorProductsIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/products/$productId/moderate': typeof AdminProductsProductIdModerateRoute
  '/admin/shops/$shopId/generator': typeof AdminShopsShopIdGeneratorRoute
  '/admin/shops/$shopId/import-export': typeof AdminShopsShopIdImportExportRoute
  '/admin/shops/$shopId/manage': typeof AdminShopsShopIdManageRoute
  '/vendor/products/$productId/edit': typeof VendorProductsProductIdEditRoute
  '/admin/shops/$shopId/products/new': typeof AdminShopsShopIdProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/category-requests': typeof AdminCategoryRequestsRoute
  '/admin/commission-orders': typeof AdminCommissionOrdersRoute
  '/admin/commissions': typeof AdminCommissionsRouteWithChildren
  '/admin/contact-settings': typeof AdminContactSettingsRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preparation': typeof AdminPreparationRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/vendors': typeof AdminVendorsRoute
  '/c/$categoryId': typeof CCategoryIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$vendorId': typeof ShopVendorIdRoute
  '/vendor/import-export': typeof VendorImportExportRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/preparation': typeof VendorPreparationRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/commissions/hub': typeof AdminCommissionsHubRoute
  '/admin/commissions/view': typeof AdminCommissionsViewRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/support/$conversationId': typeof AdminSupportConversationIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/orders/$orderId/validate-shipment': typeof OrdersOrderIdValidateShipmentRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/products/$productId/moderate': typeof AdminProductsProductIdModerateRoute
  '/admin/shops_/$shopId/generator': typeof AdminShopsShopIdGeneratorRoute
  '/admin/shops_/$shopId/import-export': typeof AdminShopsShopIdImportExportRoute
  '/admin/shops_/$shopId/manage': typeof AdminShopsShopIdManageRoute
  '/vendor/products/$productId/edit': typeof VendorProductsProductIdEditRoute
  '/admin/shops_/$shopId/products/new': typeof AdminShopsShopIdProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/become-vendor'
    | '/cart'
    | '/categories'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/orders'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/vendor'
    | '/admin/admins'
    | '/admin/categories'
    | '/admin/category-requests'
    | '/admin/commission-orders'
    | '/admin/commissions'
    | '/admin/contact-settings'
    | '/admin/countries'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/preparation'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipments'
    | '/admin/shops'
    | '/admin/support'
    | '/admin/vendors'
    | '/c/$categoryId'
    | '/product/$productId'
    | '/shop/$vendorId'
    | '/vendor/import-export'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/preparation'
    | '/vendor/reports'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/admin/'
    | '/vendor/'
    | '/admin/commissions/hub'
    | '/admin/commissions/view'
    | '/admin/customers/$userId'
    | '/admin/support/$conversationId'
    | '/api/public/inngest'
    | '/orders/$orderId/validate-shipment'
    | '/vendor/products/new'
    | '/admin/products/'
    | '/vendor/products/'
    | '/admin/products/$productId/edit'
    | '/admin/products/$productId/moderate'
    | '/admin/shops/$shopId/generator'
    | '/admin/shops/$shopId/import-export'
    | '/admin/shops/$shopId/manage'
    | '/vendor/products/$productId/edit'
    | '/admin/shops/$shopId/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/become-vendor'
    | '/cart'
    | '/categories'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/orders'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/admin/admins'
    | '/admin/categories'
    | '/admin/category-requests'
    | '/admin/commission-orders'
    | '/admin/commissions'
    | '/admin/contact-settings'
    | '/admin/countries'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/preparation'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipments'
    | '/admin/shops'
    | '/admin/support'
    | '/admin/vendors'
    | '/c/$categoryId'
    | '/product/$productId'
    | '/shop/$vendorId'
    | '/vendor/import-export'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/preparation'
    | '/vendor/reports'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/admin'
    | '/vendor'
    | '/admin/commissions/hub'
    | '/admin/commissions/view'
    | '/admin/customers/$userId'
    | '/admin/support/$conversationId'
    | '/api/public/inngest'
    | '/orders/$orderId/validate-shipment'
    | '/vendor/products/new'
    | '/admin/products'
    | '/vendor/products'
    | '/admin/products/$productId/edit'
    | '/admin/products/$productId/moderate'
    | '/admin/shops/$shopId/generator'
    | '/admin/shops/$shopId/import-export'
    | '/admin/shops/$shopId/manage'
    | '/vendor/products/$productId/edit'
    | '/admin/shops/$shopId/products/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/become-vendor'
    | '/cart'
    | '/categories'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/orders'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/vendor'
    | '/admin/admins'
    | '/admin/categories'
    | '/admin/category-requests'
    | '/admin/commission-orders'
    | '/admin/commissions'
    | '/admin/contact-settings'
    | '/admin/countries'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/preparation'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipments'
    | '/admin/shops'
    | '/admin/support'
    | '/admin/vendors'
    | '/c/$categoryId'
    | '/product/$productId'
    | '/shop/$vendorId'
    | '/vendor/import-export'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/preparation'
    | '/vendor/reports'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/admin/'
    | '/vendor/'
    | '/admin/commissions/hub'
    | '/admin/commissions/view'
    | '/admin/customers/$userId'
    | '/admin/support/$conversationId'
    | '/api/public/inngest'
    | '/orders/$orderId/validate-shipment'
    | '/vendor/products/new'
    | '/admin/products/'
    | '/vendor/products/'
    | '/admin/products/$productId/edit'
    | '/admin/products/$productId/moderate'
    | '/admin/shops_/$shopId/generator'
    | '/admin/shops_/$shopId/import-export'
    | '/admin/shops_/$shopId/manage'
    | '/vendor/products/$productId/edit'
    | '/admin/shops_/$shopId/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeVendorRoute: typeof BecomeVendorRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  VendorRoute: typeof VendorRouteWithChildren
  CCategoryIdRoute: typeof CCategoryIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ShopVendorIdRoute: typeof ShopVendorIdRoute
  ApiPublicInngestRoute: typeof ApiPublicInngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reviews': {
      id: '/vendor/reviews'
      path: '/reviews'
      fullPath: '/vendor/reviews'
      preLoaderRoute: typeof VendorReviewsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reports': {
      id: '/vendor/reports'
      path: '/reports'
      fullPath: '/vendor/reports'
      preLoaderRoute: typeof VendorReportsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/preparation': {
      id: '/vendor/preparation'
      path: '/preparation'
      fullPath: '/vendor/preparation'
      preLoaderRoute: typeof VendorPreparationRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/messages': {
      id: '/vendor/messages'
      path: '/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof VendorMessagesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/import-export': {
      id: '/vendor/import-export'
      path: '/import-export'
      fullPath: '/vendor/import-export'
      preLoaderRoute: typeof VendorImportExportRouteImport
      parentRoute: typeof VendorRoute
    }
    '/shop/$vendorId': {
      id: '/shop/$vendorId'
      path: '/shop/$vendorId'
      fullPath: '/shop/$vendorId'
      preLoaderRoute: typeof ShopVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$categoryId': {
      id: '/c/$categoryId'
      path: '/c/$categoryId'
      fullPath: '/c/$categoryId'
      preLoaderRoute: typeof CCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preparation': {
      id: '/admin/preparation'
      path: '/preparation'
      fullPath: '/admin/preparation'
      preLoaderRoute: typeof AdminPreparationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/countries': {
      id: '/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-settings': {
      id: '/admin/contact-settings'
      path: '/contact-settings'
      fullPath: '/admin/contact-settings'
      preLoaderRoute: typeof AdminContactSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commission-orders': {
      id: '/admin/commission-orders'
      path: '/commission-orders'
      fullPath: '/admin/commission-orders'
      preLoaderRoute: typeof AdminCommissionOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/category-requests': {
      id: '/admin/category-requests'
      path: '/category-requests'
      fullPath: '/admin/category-requests'
      preLoaderRoute: typeof AdminCategoryRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products/': {
      id: '/vendor/products/'
      path: '/products'
      fullPath: '/vendor/products/'
      preLoaderRoute: typeof VendorProductsIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorRoute
    }
    '/orders/$orderId/validate-shipment': {
      id: '/orders/$orderId/validate-shipment'
      path: '/$orderId/validate-shipment'
      fullPath: '/orders/$orderId/validate-shipment'
      preLoaderRoute: typeof OrdersOrderIdValidateShipmentRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/api/public/inngest': {
      id: '/api/public/inngest'
      path: '/api/public/inngest'
      fullPath: '/api/public/inngest'
      preLoaderRoute: typeof ApiPublicInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/$conversationId': {
      id: '/admin/support/$conversationId'
      path: '/$conversationId'
      fullPath: '/admin/support/$conversationId'
      preLoaderRoute: typeof AdminSupportConversationIdRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/customers/$userId': {
      id: '/admin/customers/$userId'
      path: '/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AdminCustomersUserIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/commissions/view': {
      id: '/admin/commissions/view'
      path: '/view'
      fullPath: '/admin/commissions/view'
      preLoaderRoute: typeof AdminCommissionsViewRouteImport
      parentRoute: typeof AdminCommissionsRoute
    }
    '/admin/commissions/hub': {
      id: '/admin/commissions/hub'
      path: '/hub'
      fullPath: '/admin/commissions/hub'
      preLoaderRoute: typeof AdminCommissionsHubRouteImport
      parentRoute: typeof AdminCommissionsRoute
    }
    '/vendor/products/$productId/edit': {
      id: '/vendor/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/vendor/products/$productId/edit'
      preLoaderRoute: typeof VendorProductsProductIdEditRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/shops_/$shopId/manage': {
      id: '/admin/shops_/$shopId/manage'
      path: '/shops/$shopId/manage'
      fullPath: '/admin/shops/$shopId/manage'
      preLoaderRoute: typeof AdminShopsShopIdManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops_/$shopId/import-export': {
      id: '/admin/shops_/$shopId/import-export'
      path: '/shops/$shopId/import-export'
      fullPath: '/admin/shops/$shopId/import-export'
      preLoaderRoute: typeof AdminShopsShopIdImportExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops_/$shopId/generator': {
      id: '/admin/shops_/$shopId/generator'
      path: '/shops/$shopId/generator'
      fullPath: '/admin/shops/$shopId/generator'
      preLoaderRoute: typeof AdminShopsShopIdGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId/moderate': {
      id: '/admin/products/$productId/moderate'
      path: '/$productId/moderate'
      fullPath: '/admin/products/$productId/moderate'
      preLoaderRoute: typeof AdminProductsProductIdModerateRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/shops_/$shopId/products/new': {
      id: '/admin/shops_/$shopId/products/new'
      path: '/shops/$shopId/products/new'
      fullPath: '/admin/shops/$shopId/products/new'
      preLoaderRoute: typeof AdminShopsShopIdProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminCommissionsRouteChildren {
  AdminCommissionsHubRoute: typeof AdminCommissionsHubRoute
  AdminCommissionsViewRoute: typeof AdminCommissionsViewRoute
}

const AdminCommissionsRouteChildren: AdminCommissionsRouteChildren = {
  AdminCommissionsHubRoute: AdminCommissionsHubRoute,
  AdminCommissionsViewRoute: AdminCommissionsViewRoute,
}

const AdminCommissionsRouteWithChildren =
  AdminCommissionsRoute._addFileChildren(AdminCommissionsRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersUserIdRoute: typeof AdminCustomersUserIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersUserIdRoute: AdminCustomersUserIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
  AdminProductsProductIdModerateRoute: typeof AdminProductsProductIdModerateRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
  AdminProductsProductIdModerateRoute: AdminProductsProductIdModerateRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminSupportRouteChildren {
  AdminSupportConversationIdRoute: typeof AdminSupportConversationIdRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportConversationIdRoute: AdminSupportConversationIdRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCategoryRequestsRoute: typeof AdminCategoryRequestsRoute
  AdminCommissionOrdersRoute: typeof AdminCommissionOrdersRoute
  AdminCommissionsRoute: typeof AdminCommissionsRouteWithChildren
  AdminContactSettingsRoute: typeof AdminContactSettingsRoute
  AdminCountriesRoute: typeof AdminCountriesRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPreparationRoute: typeof AdminPreparationRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminShopsShopIdGeneratorRoute: typeof AdminShopsShopIdGeneratorRoute
  AdminShopsShopIdImportExportRoute: typeof AdminShopsShopIdImportExportRoute
  AdminShopsShopIdManageRoute: typeof AdminShopsShopIdManageRoute
  AdminShopsShopIdProductsNewRoute: typeof AdminShopsShopIdProductsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCategoryRequestsRoute: AdminCategoryRequestsRoute,
  AdminCommissionOrdersRoute: AdminCommissionOrdersRoute,
  AdminCommissionsRoute: AdminCommissionsRouteWithChildren,
  AdminContactSettingsRoute: AdminContactSettingsRoute,
  AdminCountriesRoute: AdminCountriesRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPreparationRoute: AdminPreparationRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminSupportRoute: AdminSupportRouteWithChildren,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminShopsShopIdGeneratorRoute: AdminShopsShopIdGeneratorRoute,
  AdminShopsShopIdImportExportRoute: AdminShopsShopIdImportExportRoute,
  AdminShopsShopIdManageRoute: AdminShopsShopIdManageRoute,
  AdminShopsShopIdProductsNewRoute: AdminShopsShopIdProductsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdValidateShipmentRoute: typeof OrdersOrderIdValidateShipmentRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdValidateShipmentRoute: OrdersOrderIdValidateShipmentRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface VendorRouteChildren {
  VendorImportExportRoute: typeof VendorImportExportRoute
  VendorMessagesRoute: typeof VendorMessagesRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorPreparationRoute: typeof VendorPreparationRoute
  VendorReportsRoute: typeof VendorReportsRoute
  VendorReviewsRoute: typeof VendorReviewsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorProductsNewRoute: typeof VendorProductsNewRoute
  VendorProductsIndexRoute: typeof VendorProductsIndexRoute
  VendorProductsProductIdEditRoute: typeof VendorProductsProductIdEditRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorImportExportRoute: VendorImportExportRoute,
  VendorMessagesRoute: VendorMessagesRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorPreparationRoute: VendorPreparationRoute,
  VendorReportsRoute: VendorReportsRoute,
  VendorReviewsRoute: VendorReviewsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorProductsNewRoute: VendorProductsNewRoute,
  VendorProductsIndexRoute: VendorProductsIndexRoute,
  VendorProductsProductIdEditRoute: VendorProductsProductIdEditRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeVendorRoute: BecomeVendorRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  VendorRoute: VendorRouteWithChildren,
  CCategoryIdRoute: CCategoryIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ShopVendorIdRoute: ShopVendorIdRoute,
  ApiPublicInngestRoute: ApiPublicInngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
